eureka:
  instance:
    preferIpAddress: true
  client:
    initialInstanceInfoReplicationIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

transferwise:
  api:
    datetime:
      format: yyyy-MM-dd HH:mm:ss
    location:
      quote: http://localhost:12346/quote/v1